apiVersion: v1
kind: Service
metadata:
  name: movie-recommender-service
  labels:
    app: movie-recommender
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8501
    protocol: TCP
  selector:
    app: movie-recommender